# Kafka Serde Pipeline

trigger:
- main
- develop

pr:
- main
- develop

pool:
  vmImage: 'ubuntu-18.04'

jobs:
- job: PackageTest
  displayName: Package, Test, and Deploy
  steps:
  - checkout: self
    persistCredentials: true
    displayName: Checkout Code

  - task: DownloadSecureFile@1
    name: sbtCredentials
    displayName: 'SBT Credentials File'
    inputs:
      secureFile: 'sbt-credentials'

  - script: |
      mkdir -p $HOME/.sbt
      ln -s $(sbtCredentials.secureFilePath) $HOME/.sbt/.credentials
    displayName: 'Load SBT Credentials'

  - script: sbt clean +package +test
    displayName: 'Build and Test with sbt'

  - script: |
      sbt clean +publish
    displayName: Publish Dev Artifact
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))

  - script: |
      sbt "release cross with-defaults"
      git checkout develop
      git merge origin/main
      git push origin develop
    displayName: Release and tag
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
