# Kafka Serde Pipeline

trigger:
- main
- develop

pr:
- main
- develop

pool:
  vmImage: 'ubuntu-18.04'

jobs:
- job: PackageTest
  displayName: Package, Test, and Deploy
  steps:
  - checkout: self
    persistCredentials: true
    displayName: Checkout Code

  - task: DownloadSecureFile@1
    name: sbtCredentials
    displayName: 'SBT Credentials File'
    inputs:
      secureFile: 'sbt-credentials'

  - script: |
      mkdir -p $HOME/.sbt
      ln -s $(sbtCredentials.secureFilePath) $HOME/.sbt/.credentials
    displayName: 'Load SBT Credentials'

  - script: sbt clean +package +test
    displayName: 'Build and Test with sbt'

  - script: |
      sbt clean +publish
    displayName: Publish Artifacts
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'),
                                   eq(variables['Build.SourceBranch'], 'refs/heads/develop')))

  - script: |
      TAG=$(sbt -Dsbt.supershell=false -error "print version")
      TAG=$(sbt -Dsbt.supershell=false -error "print version")
      if [[ ! -z $(echo $TAG | grep SNAPSHOT) ]]; then
        echo 'cannot tag SNAPSHOT version' 1>&2
        exit 1
      fi
      git config --global user.name "AzurePipelines"
      git config --global user.email "noreply@punchcyber.com"
      git tag -a $TAG -m "Auto-tagged version from pipeline"
      git push origin $TAG
      git checkout develop
      git merge main
      git push origin develop
    displayName: Tag git version
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
